// Conteúdo do e-book: [id, nome, grupo, músculos, passos, dica, erro comum]
export const exercicios = [
  [1, 'Supino inclinado com barra', 'Peito', 'Peitoral superior (clavicular), deltoide anterior, tríceps',
    ['Deite no banco inclinado a 30–45°, pés firmes no chão e escápulas encaixadas.', 'Desça a barra de forma controlada até a parte alta do peito.', 'Empurre a barra para cima até quase estender os cotovelos.'],
    'Inclinação entre 30° e 45° mantém o foco no peitoral superior sem transferir demais para o ombro.', 'Tirar o quadril do banco para empurrar mais carga.'],
  [2, 'Supino inclinado com halteres', 'Peito', 'Peitoral superior, deltoide anterior, tríceps',
    ['Sente no banco inclinado com os halteres apoiados nas coxas e deite levando-os ao peito.', 'Desça os halteres ao lado do peito, cotovelos a cerca de 45° do tronco.', 'Empurre para cima aproximando levemente os halteres no topo.'],
    'Os halteres permitem maior amplitude que a barra — aproveite a descida completa.', 'Bater os halteres no topo e perder a tensão no peito.'],
  [3, 'Crucifixo inclinado com halteres', 'Peito', 'Peitoral superior, deltoide anterior',
    ['Deite no banco inclinado com os halteres acima do peito e cotovelos levemente flexionados.', 'Abra os braços em arco até sentir alongamento no peito.', 'Retorne pelo mesmo arco, como se abraçasse uma árvore.'],
    'Mantenha o ângulo do cotovelo fixo durante todo o movimento.', 'Flexionar e estender os cotovelos, transformando o exercício em supino.'],
  [4, 'Crossover de baixo para cima', 'Peito', 'Peitoral superior, deltoide anterior',
    ['Posicione as polias na altura mais baixa e fique no centro com um passo à frente.', 'Com cotovelos levemente flexionados, leve as mãos para cima e para dentro.', 'Una as mãos na altura do queixo e retorne devagar.'],
    'Pense em "levar os bíceps em direção ao rosto" para ativar melhor a porção superior.', 'Usar o impulso do tronco para subir a carga.'],
  [5, 'Supino reto com barra', 'Peito', 'Peitoral maior, deltoide anterior, tríceps',
    ['Deite no banco com olhos sob a barra, pés no chão e escápulas retraídas.', 'Desça a barra até tocar levemente a linha dos mamilos.', 'Empurre a barra para cima e levemente para trás, sobre os ombros.'],
    'Pegada um pouco mais larga que os ombros e antebraços verticais na posição baixa.', 'Quicar a barra no peito para ganhar impulso.'],
  [6, 'Supino reto com halteres', 'Peito', 'Peitoral maior, deltoide anterior, tríceps',
    ['Deite no banco reto com os halteres na altura do peito.', 'Desça controlando até sentir alongamento no peitoral.', 'Empurre os halteres para cima até quase estender os braços.'],
    'Excelente para corrigir desequilíbrios entre os lados.', 'Abrir demais os cotovelos (90°), sobrecarregando o ombro.'],
  [7, 'Peck deck (voador)', 'Peito', 'Peitoral maior, deltoide anterior',
    ['Ajuste o banco para que as manoplas fiquem na altura do peito.', 'Com as costas apoiadas, feche os braços à frente contraindo o peito.', 'Retorne lentamente até sentir o alongamento.'],
    'Segure 1 segundo na contração máxima para aumentar o estímulo.', 'Deixar o peso "bater" na volta e perder o controle.'],
  [8, 'Flexão de braço', 'Peito', 'Peitoral maior, tríceps, deltoide anterior, core',
    ['Apoie mãos um pouco mais largas que os ombros e corpo em linha reta.', 'Desça o peito até próximo do chão mantendo o abdômen firme.', 'Empurre o chão e volte à posição inicial.'],
    'Iniciantes podem apoiar os joelhos; avançados podem elevar os pés.', 'Deixar o quadril cair ou empinar.'],
  [9, 'Supino declinado com barra', 'Peito', 'Peitoral inferior, tríceps, deltoide anterior',
    ['Prenda as pernas no apoio do banco declinado e deite.', 'Desça a barra até a parte baixa do peito.', 'Empurre até quase estender os cotovelos.'],
    'Use um parceiro para tirar e recolocar a barra no suporte.', 'Descer a barra no pescoço em vez da parte baixa do peito.'],
  [10, 'Mergulho nas paralelas', 'Peito', 'Peitoral inferior, tríceps, deltoide anterior',
    ['Suspenda o corpo nas barras paralelas com braços estendidos.', 'Incline o tronco à frente e desça até os ombros ficarem na altura dos cotovelos.', 'Empurre para cima até estender os braços.'],
    'Tronco inclinado foca no peito; tronco reto foca no tríceps.', 'Descer demais, forçando a articulação do ombro.'],
  [11, 'Crossover de cima para baixo', 'Peito', 'Peitoral inferior e esternal',
    ['Posicione as polias no alto e dê um passo à frente.', 'Leve as mãos para baixo e para dentro em arco, até a frente do quadril.', 'Retorne de forma controlada até a altura dos ombros.'],
    'Cruzar levemente as mãos no final aumenta a contração.', 'Curvar demais o tronco e usar o peso do corpo.'],
  [12, 'Puxada frontal aberta', 'Costas', 'Latíssimo do dorso, redondo maior, bíceps',
    ['Sente no pulley, prenda as coxas e segure a barra com pegada aberta.', 'Puxe a barra até a parte alta do peito, levando os cotovelos para baixo.', 'Retorne devagar até estender os braços.'],
    'Pense em puxar com os cotovelos, não com as mãos.', 'Jogar o tronco para trás e puxar com balanço.'],
  [13, 'Barra fixa pronada', 'Costas', 'Latíssimo do dorso, bíceps, romboides',
    ['Segure a barra com as palmas para frente, pouco mais largas que os ombros.', 'Puxe o corpo até o queixo passar a barra.', 'Desça controlando até estender os braços.'],
    'Use elástico ou máquina graviton se ainda não consegue fazer repetições completas.', 'Fazer "meia repetição" sem estender os braços.'],
  [14, 'Pulldown com braços estendidos', 'Costas', 'Latíssimo do dorso, redondo maior',
    ['Em pé diante da polia alta, segure a barra com braços estendidos.', 'Leve a barra até as coxas em arco, mantendo os cotovelos quase retos.', 'Retorne até a altura da cabeça sentindo o alongamento.'],
    'Ótimo exercício de isolamento para "sentir" a dorsal antes das puxadas.', 'Flexionar os cotovelos e transformar em tríceps.'],
  [15, 'Remada curvada com barra', 'Costas', 'Latíssimo, romboides, trapézio médio, bíceps',
    ['Incline o tronco à frente (cerca de 45°) com joelhos levemente flexionados.', 'Puxe a barra em direção ao umbigo, unindo as escápulas.', 'Desça a barra de forma controlada.'],
    'Coluna neutra do início ao fim — trave o abdômen.', 'Arredondar a lombar durante o movimento.'],
  [16, 'Remada baixa sentada', 'Costas', 'Romboides, trapézio médio, latíssimo, bíceps',
    ['Sente com os pés apoiados e segure o triângulo com os braços estendidos.', 'Puxe até o abdômen, estufando o peito e unindo as escápulas.', 'Retorne estendendo os braços sem arredondar as costas.'],
    'Mantenha o tronco praticamente parado; o movimento é dos braços e escápulas.', 'Balançar o tronco para frente e para trás.'],
  [17, 'Remada unilateral com halter (serrote)', 'Costas', 'Latíssimo do dorso, romboides, bíceps',
    ['Apoie joelho e mão do mesmo lado no banco, costas paralelas ao chão.', 'Puxe o halter em direção ao quadril.', 'Desça até estender o braço.'],
    'Levar o halter ao quadril (e não ao peito) aumenta o trabalho da dorsal.', 'Girar o tronco para subir o peso.'],
  [18, 'Encolhimento com barra', 'Trapézio', 'Trapézio superior',
    ['Em pé, segure a barra à frente das coxas com braços estendidos.', 'Eleve os ombros em direção às orelhas.', 'Segure 1 segundo e desça devagar.'],
    'Movimento apenas vertical — não é preciso girar os ombros.', 'Flexionar os cotovelos durante a subida.'],
  [19, 'Encolhimento com halteres', 'Trapézio', 'Trapézio superior',
    ['Em pé, halteres ao lado do corpo com palmas voltadas para dentro.', 'Eleve os ombros o mais alto possível.', 'Desça lentamente.'],
    'Halteres ao lado do corpo deixam o movimento mais natural que a barra.', 'Usar carga excessiva com amplitude mínima.'],
  [20, 'Remada alta com barra', 'Ombros', 'Deltoide lateral, trapézio superior',
    ['Segure a barra à frente das coxas com pegada na largura dos ombros.', 'Puxe a barra até a altura do peito, cotovelos acima das mãos.', 'Desça de forma controlada.'],
    'Pegada mais aberta reduz o estresse no ombro.', 'Subir a barra acima da linha do peito, causando pinçamento.'],
  [21, 'Levantamento terra', 'Posterior / Lombar', 'Glúteos, isquiotibiais, eretores da espinha, trapézio',
    ['Pés na largura do quadril, barra sobre o meio do pé.', 'Segure a barra, trave as costas e empurre o chão com as pernas.', 'Estenda quadril e joelhos juntos até ficar ereto; desça o caminho inverso.'],
    'A barra deve "raspar" nas pernas durante todo o movimento.', 'Arredondar a lombar para pegar a barra.'],
  [22, 'Hiperextensão lombar 45°', 'Posterior / Lombar', 'Eretores da espinha, glúteos, isquiotibiais',
    ['Ajuste o apoio na altura do quadril e cruze os braços no peito.', 'Desça o tronco dobrando no quadril.', 'Suba até o corpo ficar alinhado, sem hiperestender.'],
    'Para focar em glúteos, arredonde levemente as costas e aperte o glúteo na subida.', 'Subir além da linha do corpo, hiperestendendo a lombar.'],
  [23, 'Bom dia (good morning)', 'Posterior / Lombar', 'Isquiotibiais, eretores da espinha, glúteos',
    ['Barra apoiada no trapézio, pés na largura do quadril, joelhos levemente flexionados.', 'Incline o tronco à frente levando o quadril para trás.', 'Volte à posição inicial contraindo glúteos e posteriores.'],
    'Comece com carga leve: é um exercício técnico.', 'Flexionar demais os joelhos, virando um agachamento.'],
  [24, 'Desenvolvimento com halteres', 'Ombros', 'Deltoide anterior e lateral, tríceps',
    ['Sente com encosto a 90° e halteres na altura das orelhas.', 'Empurre os halteres acima da cabeça.', 'Desça até os cotovelos ficarem na altura dos ombros.'],
    'Cotovelos levemente à frente do corpo protegem o ombro.', 'Arquear a lombar para empurrar mais carga.'],
  [25, 'Elevação frontal com halteres', 'Ombros', 'Deltoide anterior',
    ['Em pé, halteres à frente das coxas.', 'Eleve os braços à frente até a altura dos ombros.', 'Desça devagar.'],
    'Pode ser feito alternado para maior controle.', 'Balançar o corpo para levantar o peso.'],
  [26, 'Desenvolvimento militar com barra', 'Ombros', 'Deltoides, tríceps, trapézio superior',
    ['Em pé, barra apoiada na parte alta do peito, pegada na largura dos ombros.', 'Empurre a barra acima da cabeça, passando o rosto.', 'Desça até a parte alta do peito.'],
    'Contraia glúteos e abdômen para estabilizar a coluna.', 'Empurrar com as pernas (vira push press).'],
  [27, 'Elevação lateral com halteres', 'Ombros', 'Deltoide lateral',
    ['Em pé, halteres ao lado do corpo, cotovelos levemente flexionados.', 'Eleve os braços lateralmente até a altura dos ombros.', 'Desça de forma lenta e controlada.'],
    'Lidere o movimento com os cotovelos, não com as mãos.', 'Usar carga pesada e subir com impulso.'],
  [28, 'Elevação lateral unilateral na polia', 'Ombros', 'Deltoide lateral',
    ['Fique de lado para a polia baixa e segure o cabo com a mão oposta.', 'Eleve o braço lateralmente até a altura do ombro.', 'Retorne devagar cruzando à frente do corpo.'],
    'A polia mantém tensão constante, inclusive no início do movimento.', 'Inclinar o tronco para longe da polia para roubar.'],
  [29, 'Elevação lateral na máquina', 'Ombros', 'Deltoide lateral',
    ['Ajuste o banco para alinhar o eixo da máquina com o ombro.', 'Eleve os braços lateralmente empurrando os apoios.', 'Desça controlando.'],
    'Ótima para séries até a falha com segurança.', 'Elevar os ombros (encolher) durante a subida.'],
  [30, 'Crucifixo inverso na máquina', 'Ombros', 'Deltoide posterior, romboides, trapézio médio',
    ['Sente de frente para o encosto e segure as manoplas na altura dos ombros.', 'Abra os braços para trás em arco.', 'Retorne lentamente.'],
    'Mantenha o peito colado no apoio durante toda a série.', 'Afastar o tronco do encosto para usar impulso.'],
  [31, 'Crucifixo inverso curvado com halteres', 'Ombros', 'Deltoide posterior, romboides',
    ['Incline o tronco à frente com costas retas e halteres pendurados.', 'Abra os braços lateralmente até a linha dos ombros.', 'Desça de forma controlada.'],
    'Cargas leves e alta concentração funcionam melhor aqui.', 'Arredondar as costas durante o exercício.'],
  [32, 'Face pull', 'Ombros', 'Deltoide posterior, manguito rotador, trapézio médio',
    ['Polia na altura do rosto com corda; segure com as palmas para baixo.', 'Puxe a corda em direção ao rosto, abrindo as mãos para os lados.', 'Retorne estendendo os braços.'],
    'Excelente para postura e saúde dos ombros — inclua em todo treino de costas.', 'Puxar a corda para o pescoço com os cotovelos baixos.'],
  [33, 'Rosca inclinada com halteres', 'Bíceps', 'Bíceps braquial (cabeça longa)',
    ['Deite em banco inclinado a 45–60°, braços pendurados.', 'Flexione os cotovelos levando os halteres aos ombros.', 'Desça até estender totalmente os braços.'],
    'A posição alonga a cabeça longa do bíceps, aumentando o estímulo.', 'Levar os cotovelos à frente durante a subida.'],
  [34, 'Rosca bayesian na polia', 'Bíceps', 'Bíceps braquial (cabeça longa)',
    ['De costas para a polia baixa, segure o cabo com o braço estendido para trás.', 'Flexione o cotovelo sem mover o braço.', 'Retorne até o alongamento completo.'],
    'Dê um passo à frente para aumentar o alongamento no início.', 'Deixar o ombro ir para frente junto com o cotovelo.'],
  [35, 'Rosca direta pegada fechada', 'Bíceps', 'Bíceps braquial (cabeça longa), braquial',
    ['Em pé, segure a barra com as mãos próximas.', 'Flexione os cotovelos levando a barra ao peito.', 'Desça de forma controlada.'],
    'Cotovelos colados ao corpo do início ao fim.', 'Balançar o tronco para subir a barra.'],
  [36, 'Rosca Scott com barra W', 'Bíceps', 'Bíceps braquial (cabeça curta), braquial',
    ['Apoie a parte de trás dos braços no banco Scott.', 'Flexione levando a barra em direção aos ombros.', 'Desça até quase estender os cotovelos.'],
    'A barra W reduz o estresse nos punhos.', 'Estender totalmente e "soltar" o peso no final.'],
  [37, 'Rosca concentrada', 'Bíceps', 'Bíceps braquial',
    ['Sentado, apoie o cotovelo na parte interna da coxa.', 'Flexione o cotovelo levando o halter ao ombro.', 'Desça devagar até estender.'],
    'Gire levemente o punho para fora no topo (supinação) para máxima contração.', 'Mover o ombro para ajudar a subir.'],
  [38, 'Rosca alternada sentado', 'Bíceps', 'Bíceps braquial, braquial',
    ['Sente com os halteres ao lado do corpo, palmas para dentro.', 'Suba um halter girando a palma para cima.', 'Desça e repita com o outro braço.'],
    'Sentado reduz a chance de balançar o corpo.', 'Acelerar a descida.'],
  [39, 'Rosca na polia baixa', 'Bíceps', 'Bíceps braquial',
    ['De frente para a polia baixa, segure a barra com as palmas para cima.', 'Flexione os cotovelos levando a barra ao peito.', 'Retorne estendendo os braços.'],
    'A polia mantém tensão constante durante todo o movimento.', 'Afastar os cotovelos do corpo.'],
  [40, 'Rosca martelo', 'Bíceps', 'Braquial, braquiorradial, bíceps',
    ['Em pé, halteres ao lado do corpo com palmas voltadas uma para a outra.', 'Flexione os cotovelos mantendo a pegada neutra.', 'Desça devagar.'],
    'Ótimo para engrossar o braço e o antebraço.', 'Girar o punho durante o movimento.'],
  [41, 'Rosca inversa com barra', 'Antebraço', 'Braquiorradial, braquial, extensores do punho',
    ['Segure a barra com as palmas para baixo, na largura dos ombros.', 'Flexione os cotovelos levando a barra ao peito.', 'Desça de forma controlada.'],
    'Use carga menor que na rosca direta.', 'Deixar os punhos dobrarem para baixo.'],
  [42, 'Rosca martelo na polia com corda', 'Bíceps', 'Braquial, braquiorradial',
    ['Polia baixa com corda, pegada neutra.', 'Flexione os cotovelos levando a corda aos ombros.', 'Desça até estender os braços.'],
    'Afaste as pontas da corda no topo para contrair mais.', 'Inclinar o tronco para trás.'],
  [43, 'Tríceps francês com halter', 'Tríceps', 'Tríceps braquial (cabeça longa)',
    ['Sentado, segure um halter com as duas mãos acima da cabeça.', 'Flexione os cotovelos descendo o halter atrás da cabeça.', 'Estenda os braços voltando ao topo.'],
    'Mantenha os cotovelos apontando para frente, próximos à cabeça.', 'Abrir os cotovelos para os lados.'],
  [44, 'Tríceps testa com barra W', 'Tríceps', 'Tríceps braquial',
    ['Deitado, segure a barra W acima do peito com braços estendidos.', 'Flexione os cotovelos descendo a barra em direção à testa.', 'Estenda os braços de volta.'],
    'Levar a barra um pouco atrás da cabeça aumenta o trabalho da cabeça longa.', 'Mover os ombros e transformar em pullover.'],
  [45, 'Extensão acima da cabeça na polia', 'Tríceps', 'Tríceps braquial (cabeça longa)',
    ['De costas para a polia, segure a corda acima da cabeça.', 'Estenda os cotovelos levando as mãos à frente.', 'Retorne até sentir o alongamento.'],
    'Um dos melhores exercícios para a cabeça longa do tríceps.', 'Mover os braços em vez de apenas os cotovelos.'],
  [46, 'Tríceps pulley com barra reta', 'Tríceps', 'Tríceps braquial (cabeças lateral e medial)',
    ['De frente para a polia alta, segure a barra com as palmas para baixo.', 'Estenda os cotovelos empurrando a barra até as coxas.', 'Retorne até os antebraços ficarem paralelos ao chão.'],
    'Cotovelos fixos ao lado do corpo.', 'Inclinar o corpo sobre a barra para empurrar mais peso.'],
  [47, 'Tríceps coice com halter', 'Tríceps', 'Tríceps braquial',
    ['Incline o tronco com o braço paralelo ao chão e cotovelo a 90°.', 'Estenda o cotovelo levando o halter para trás.', 'Retorne a 90°.'],
    'Segure a contração 1 segundo com o braço estendido.', 'Deixar o cotovelo cair durante a série.'],
  [48, 'Supino fechado', 'Tríceps', 'Tríceps braquial, peitoral, deltoide anterior',
    ['Deite no banco e segure a barra na largura dos ombros.', 'Desça a barra até a parte baixa do peito com cotovelos próximos ao corpo.', 'Empurre até estender os braços.'],
    'Não precisa de pegada muito fechada — largura dos ombros protege os punhos.', 'Abrir os cotovelos, tirando o foco do tríceps.'],
  [49, 'Tríceps unilateral pegada supinada', 'Tríceps', 'Tríceps braquial (cabeça medial)',
    ['Na polia alta, segure o pegador com a palma para cima.', 'Estenda o cotovelo até o braço ficar reto.', 'Retorne devagar.'],
    'Faça sem pressa, focando na contração.', 'Afastar o cotovelo do tronco.'],
  [50, 'Mergulho no banco', 'Tríceps', 'Tríceps braquial, deltoide anterior',
    ['Apoie as mãos na borda do banco atrás do corpo e estenda as pernas.', 'Flexione os cotovelos descendo o quadril.', 'Empurre até estender os braços.'],
    'Joelhos flexionados deixam mais fácil; pés elevados, mais difícil.', 'Descer demais, forçando o ombro.'],
  [51, 'Tríceps na polia com corda', 'Tríceps', 'Tríceps braquial (cabeça lateral)',
    ['Segure a corda na polia alta com pegada neutra.', 'Estenda os cotovelos abrindo a corda no final.', 'Retorne controlando.'],
    'Abrir a corda no final aumenta a contração da cabeça lateral.', 'Deixar os cotovelos subirem na volta.'],
  [52, 'Rosca de punho com barra', 'Antebraço', 'Flexores do punho',
    ['Sentado, antebraços apoiados nas coxas, palmas para cima.', 'Flexione os punhos elevando a barra.', 'Desça até alongar os flexores.'],
    'Deixe a barra rolar até os dedos na descida para mais amplitude.', 'Levantar os antebraços das coxas.'],
  [53, 'Caminhada do fazendeiro', 'Antebraço', 'Antebraços, trapézio, core, pernas',
    ['Segure halteres ou kettlebells pesados ao lado do corpo.', 'Caminhe com passos curtos e postura ereta.', 'Percorra a distância ou tempo definido e apoie a carga com segurança.'],
    'Um dos melhores exercícios para pegada e estabilidade geral.', 'Inclinar o corpo para um lado.'],
  [54, 'Suspensão na barra', 'Antebraço', 'Flexores do antebraço, latíssimo, ombros',
    ['Segure a barra fixa com pegada pronada.', 'Fique suspenso com os braços estendidos e ombros ativos.', 'Mantenha pelo tempo definido.'],
    'Também ajuda a descomprimir a coluna.', 'Relaxar totalmente os ombros até as orelhas.'],
  [55, 'Rosca de punho inversa com halter', 'Antebraço', 'Extensores do punho',
    ['Apoie o antebraço na coxa ou banco com a palma para baixo.', 'Estenda o punho elevando o halter.', 'Desça devagar.'],
    'Use cargas leves — os extensores são músculos pequenos.', 'Mover o antebraço junto.'],
  [56, 'Enrolador de punho', 'Antebraço', 'Flexores e extensores do punho',
    ['Segure o rolo com braços estendidos à frente.', 'Gire os punhos alternadamente enrolando a corda até o peso subir.', 'Desenrole devagar até o peso descer.'],
    'Faça nos dois sentidos para trabalhar flexores e extensores.', 'Baixar os braços durante a série.'],
  [57, 'Desvio radial com halter', 'Antebraço', 'Músculos radiais do punho',
    ['Em pé, segure a ponta de um halter com o braço ao lado do corpo.', 'Eleve a ponta do halter à frente, inclinando o punho.', 'Retorne devagar.'],
    'Movimento curto: só o punho se move.', 'Flexionar o cotovelo.'],
  [58, 'Abdominal supra', 'Abdômen', 'Reto abdominal (porção superior)',
    ['Deite com joelhos flexionados e pés no chão.', 'Eleve os ombros do chão contraindo o abdômen.', 'Desça devagar sem relaxar totalmente.'],
    'Solte o ar ao subir.', 'Puxar a cabeça com as mãos.'],
  [59, 'Abdominal na polia ajoelhado', 'Abdômen', 'Reto abdominal',
    ['Ajoelhe de frente para a polia alta segurando a corda ao lado da cabeça.', 'Flexione o tronco levando os cotovelos em direção às coxas.', 'Retorne devagar.'],
    'Permite progressão de carga, como qualquer outro músculo.', 'Sentar sobre os calcanhares e usar o quadril.'],
  [60, 'Abdominal no banco declinado', 'Abdômen', 'Reto abdominal, oblíquos',
    ['Prenda os pés no banco declinado.', 'Suba o tronco enrolando a coluna.', 'Desça controlando.'],
    'Segure uma anilha no peito para progredir.', 'Descer de uma vez, sem controle.'],
  [61, 'Elevação de pernas suspenso', 'Abdômen', 'Reto abdominal (porção inferior), flexores do quadril',
    ['Suspenda-se na barra fixa com braços estendidos.', 'Eleve as pernas estendidas até a altura do quadril ou acima.', 'Desça devagar sem balançar.'],
    'Enrole a pelve para cima no topo para ativar mais o abdômen.', 'Balançar o corpo para subir as pernas.'],
  [62, 'Abdominal infra reverso', 'Abdômen', 'Reto abdominal (porção inferior)',
    ['Deite com as pernas elevadas e joelhos flexionados.', 'Eleve o quadril do chão levando os joelhos ao peito.', 'Desça devagar.'],
    'Pense em "enrolar" a pelve, não em balançar as pernas.', 'Usar impulso das pernas.'],
  [63, 'Elevação de joelhos na paralela', 'Abdômen', 'Reto abdominal, flexores do quadril',
    ['Apoie os antebraços na paralela com as costas no encosto.', 'Eleve os joelhos em direção ao peito.', 'Desça de forma controlada.'],
    'Mantenha as costas coladas no encosto.', 'Balançar as pernas.'],
  [64, 'Flexão lateral com halter', 'Abdômen', 'Oblíquos, quadrado lombar',
    ['Em pé, segure um halter em uma mão.', 'Incline o tronco para o lado do halter.', 'Volte contraindo o lado oposto.'],
    'Faça um lado por vez, com um halter só.', 'Segurar halteres nos dois lados (anula o exercício).'],
  [65, 'Lenhador na polia (woodchopper)', 'Abdômen', 'Oblíquos, core',
    ['Polia alta ao lado do corpo, segure com as duas mãos.', 'Puxe em diagonal para baixo, girando o tronco.', 'Retorne controlando.'],
    'O giro vem do tronco; os braços apenas guiam.', 'Girar só os braços.'],
  [66, 'Prancha lateral com elevação de quadril', 'Abdômen', 'Oblíquos, glúteo médio, core',
    ['Apoie o antebraço no chão com o corpo alinhado de lado.', 'Desça o quadril em direção ao chão.', 'Eleve o quadril acima da linha do corpo.'],
    'Mantenha o cotovelo exatamente abaixo do ombro.', 'Girar o tronco para frente.'],
  [67, 'Prancha frontal', 'Abdômen', 'Transverso, reto abdominal, core',
    ['Apoie antebraços e pontas dos pés no chão.', 'Mantenha o corpo reto da cabeça aos calcanhares.', 'Sustente pelo tempo definido respirando normalmente.'],
    'Contraia glúteos e abdômen ao mesmo tempo.', 'Deixar o quadril cair.'],
  [68, 'Roda abdominal', 'Abdômen', 'Reto abdominal, transverso, latíssimo',
    ['Ajoelhe segurando a roda à frente.', 'Role para frente estendendo o corpo sem arquear a lombar.', 'Puxe de volta contraindo o abdômen.'],
    'Comece com amplitudes curtas e aumente aos poucos.', 'Arquear a lombar na extensão.'],
  [69, 'Dead bug', 'Abdômen', 'Transverso, reto abdominal',
    ['Deite com braços estendidos para cima e joelhos a 90°.', 'Estenda braço e perna opostos, mantendo a lombar no chão.', 'Retorne e alterne os lados.'],
    'Excelente para iniciantes e para quem tem dor lombar.', 'Tirar a lombar do chão.'],
  [70, 'Cadeira extensora', 'Quadríceps', 'Quadríceps',
    ['Ajuste o encosto para o joelho alinhar ao eixo da máquina.', 'Estenda os joelhos até as pernas ficarem retas.', 'Desça controlando.'],
    'Segure 1 segundo na extensão máxima.', 'Tirar o quadril do banco.'],
  [71, 'Agachamento sissy', 'Quadríceps', 'Quadríceps (reto femoral)',
    ['Segure um apoio e fique na ponta dos pés.', 'Leve os joelhos à frente inclinando o tronco para trás.', 'Volte contraindo o quadríceps.'],
    'Exercício avançado: comece com amplitudes curtas.', 'Dobrar o quadril em vez de manter o corpo alinhado.'],
  [72, 'Flexão de quadril na polia', 'Quadríceps', 'Iliopsoas, reto femoral',
    ['Prenda a tornozeleira na polia baixa e fique de costas para ela.', 'Eleve a perna à frente flexionando o quadril.', 'Retorne devagar.'],
    'Mantenha o tronco ereto segurando em um apoio.', 'Inclinar o tronco para trás.'],
  [73, 'Leg press 45° pés estreitos', 'Quadríceps', 'Quadríceps, glúteos',
    ['Sente com os pés próximos e no centro da plataforma.', 'Destrave e desça até os joelhos formarem cerca de 90°.', 'Empurre sem travar os joelhos.'],
    'Pés baixos e estreitos focam mais o quadríceps.', 'Tirar o quadril do banco no final da descida.'],
  [74, 'Agachamento hack', 'Quadríceps', 'Quadríceps, glúteos',
    ['Costas no encosto e ombros sob os apoios.', 'Desça flexionando os joelhos até 90° ou mais.', 'Empurre a plataforma até quase estender.'],
    'Permite agachar pesado com mais estabilidade que o livre.', 'Tirar os calcanhares da plataforma.'],
  [75, 'Agachamento livre com barra', 'Quadríceps', 'Quadríceps, glúteos, adutores, core',
    ['Barra apoiada no trapézio, pés na largura dos ombros.', 'Desça levando o quadril para trás e para baixo até a coxa ficar paralela.', 'Suba empurrando o chão com o pé inteiro.'],
    'Joelhos seguem a direção das pontas dos pés.', 'Joelhos entrando para dentro na subida.'],
  [76, 'Agachamento búlgaro', 'Quadríceps', 'Quadríceps, glúteos',
    ['Apoie o peito do pé de trás em um banco.', 'Desça o joelho de trás em direção ao chão.', 'Suba empurrando com a perna da frente.'],
    'Tronco ereto = mais quadríceps; tronco inclinado = mais glúteo.', 'Perna da frente muito próxima do banco.'],
  [77, 'Agachamento frontal', 'Quadríceps', 'Quadríceps, core, glúteos',
    ['Barra apoiada na frente dos ombros, cotovelos altos.', 'Desça mantendo o tronco o mais vertical possível.', 'Suba mantendo os cotovelos elevados.'],
    'Excelente para quadríceps e postura.', 'Deixar os cotovelos caírem e a barra rolar.'],
  [78, 'Subida no banco (step up)', 'Quadríceps', 'Quadríceps, glúteos',
    ['De frente para um banco, apoie um pé inteiro nele.', 'Suba empurrando com a perna de cima.', 'Desça controlando.'],
    'Evite impulsionar com a perna de baixo.', 'Banco alto demais para a sua mobilidade.'],
  [79, 'Stiff com barra', 'Posterior de coxa', 'Isquiotibiais, glúteos, eretores',
    ['Em pé, barra à frente das coxas, joelhos levemente flexionados.', 'Desça a barra rente às pernas levando o quadril para trás.', 'Suba contraindo glúteos e posteriores.'],
    'Desça até sentir alongamento forte atrás da coxa, sem arredondar as costas.', 'Arredondar a lombar para descer mais.'],
  [80, 'Levantamento romeno com halteres', 'Posterior de coxa', 'Isquiotibiais, glúteos',
    ['Halteres à frente das coxas, joelhos levemente flexionados.', 'Leve o quadril para trás descendo os halteres rente às pernas.', 'Volte empurrando o quadril à frente.'],
    'Pense em "fechar uma porta com o bumbum".', 'Transformar em agachamento dobrando muito os joelhos.'],
  [81, 'Stiff unilateral com halter', 'Posterior de coxa', 'Isquiotibiais, glúteos, estabilizadores',
    ['Em uma perna, segure um halter na mão oposta.', 'Incline o tronco à frente levando a perna livre para trás.', 'Volte à posição inicial.'],
    'Olhe para um ponto fixo no chão para manter o equilíbrio.', 'Girar o quadril para o lado.'],
  [82, 'Mesa flexora', 'Posterior de coxa', 'Isquiotibiais',
    ['Deite de bruços com o rolo acima dos calcanhares.', 'Flexione os joelhos levando os calcanhares ao glúteo.', 'Desça controlando.'],
    'Mantenha o quadril colado no banco.', 'Levantar o quadril para ajudar.'],
  [83, 'Cadeira flexora', 'Posterior de coxa', 'Isquiotibiais',
    ['Sente com o rolo sob os calcanhares e trave as coxas.', 'Flexione os joelhos puxando o rolo para baixo.', 'Retorne devagar.'],
    'A posição sentada alonga mais os posteriores — ótima para hipertrofia.', 'Descer rápido, perdendo o controle.'],
  [84, 'Flexora em pé unilateral', 'Posterior de coxa', 'Isquiotibiais',
    ['Apoie-se na máquina com o rolo atrás do tornozelo.', 'Flexione o joelho levando o calcanhar ao glúteo.', 'Desça devagar.'],
    'Trabalhar uma perna por vez corrige assimetrias.', 'Mover o quadril junto.'],
  [85, 'Flexão nórdica', 'Posterior de coxa', 'Isquiotibiais',
    ['Ajoelhe com os tornozelos presos.', 'Incline o corpo à frente lentamente resistindo com os posteriores.', 'Apoie as mãos no chão e empurre para voltar.'],
    'Exercício avançado e ótimo para prevenção de lesões.', 'Dobrar o quadril em vez de manter o corpo reto.'],
  [86, 'Elevação pélvica com barra (hip thrust)', 'Glúteos', 'Glúteo máximo, isquiotibiais',
    ['Apoie as costas no banco e a barra sobre o quadril (use protetor).', 'Empurre o quadril para cima até o corpo ficar alinhado.', 'Desça controlando.'],
    'Queixo levemente para baixo e costelas "fechadas" no topo.', 'Hiperestender a lombar em vez de contrair o glúteo.'],
  [87, 'Coice na polia', 'Glúteos', 'Glúteo máximo',
    ['Prenda a tornozeleira na polia baixa e fique de frente para ela.', 'Estenda o quadril levando a perna para trás.', 'Retorne devagar.'],
    'Incline levemente o tronco à frente para ganhar amplitude.', 'Arquear a lombar para subir mais a perna.'],
  [88, 'Ponte de glúteo unilateral', 'Glúteos', 'Glúteo máximo, isquiotibiais',
    ['Deite com um pé no chão e a outra perna estendida.', 'Eleve o quadril empurrando com o calcanhar.', 'Desça devagar.'],
    'Ótimo para treino em casa e ativação antes do treino de pernas.', 'Deixar o quadril girar para um lado.'],
  [89, 'Cadeira abdutora', 'Glúteos', 'Glúteo médio e mínimo',
    ['Sente com as pernas nos apoios.', 'Abra as pernas empurrando os apoios para fora.', 'Retorne controlando.'],
    'Segure 1 segundo com as pernas abertas.', 'Deixar o peso bater na volta.'],
  [90, 'Abdução de quadril na polia', 'Glúteos', 'Glúteo médio e mínimo',
    ['Tornozeleira na polia baixa, de lado para ela.', 'Eleve a perna lateralmente.', 'Retorne devagar.'],
    'Mantenha a ponta do pé para frente.', 'Inclinar o tronco para o lado.'],
  [91, 'Caminhada lateral com mini band', 'Glúteos', 'Glúteo médio',
    ['Mini band acima dos joelhos ou nos tornozelos, semi-agachado.', 'Dê passos laterais mantendo a tensão no elástico.', 'Volte na direção oposta.'],
    'Ótimo como aquecimento de glúteos.', 'Deixar os pés se aproximarem demais.'],
  [92, 'Abdução deitado de lado', 'Glúteos', 'Glúteo médio',
    ['Deite de lado com as pernas estendidas.', 'Eleve a perna de cima.', 'Desça devagar.'],
    'Deixe a perna levemente para trás e o pé apontado para frente.', 'Girar o pé para cima (usa o flexor do quadril).'],
  [93, 'Cadeira abdutora com tronco inclinado', 'Glúteos', 'Glúteo médio e máximo (porção superior)',
    ['Sente na abdutora e incline o tronco à frente.', 'Abra as pernas empurrando os apoios.', 'Retorne controlando.'],
    'A inclinação aumenta o recrutamento do glúteo máximo.', 'Voltar o tronco durante a série.'],
  [94, 'Abdução em pé com caneleira', 'Glúteos', 'Glúteo médio',
    ['Em pé com a caneleira, segure um apoio.', 'Eleve a perna lateralmente.', 'Desça devagar.'],
    'Opção prática para treinar em casa.', 'Inclinar o tronco para compensar.'],
  [95, 'Panturrilha em pé na máquina', 'Panturrilha', 'Gastrocnêmio',
    ['Ombros sob os apoios e ponta dos pés na plataforma.', 'Eleve os calcanhares o máximo possível.', 'Desça até alongar totalmente.'],
    'Pausa de 1–2 segundos embaixo elimina o efeito "mola".', 'Amplitude curta e rápida.'],
  [96, 'Panturrilha no leg press', 'Panturrilha', 'Gastrocnêmio',
    ['Apoie a ponta dos pés na borda inferior da plataforma.', 'Empurre a plataforma estendendo os tornozelos.', 'Retorne até alongar.'],
    'Mantenha a trava de segurança sempre ao alcance.', 'Flexionar os joelhos durante o movimento.'],
  [97, 'Panturrilha unilateral no degrau', 'Panturrilha', 'Gastrocnêmio, sóleo',
    ['Apoie a ponta de um pé no degrau segurando em um apoio.', 'Eleve o calcanhar.', 'Desça abaixo do nível do degrau.'],
    'Segure um halter para aumentar a carga.', 'Não descer abaixo do degrau.'],
  [98, 'Panturrilha sentado na máquina', 'Panturrilha', 'Sóleo',
    ['Sente com o apoio sobre as coxas e pontas dos pés na plataforma.', 'Eleve os calcanhares.', 'Desça até alongar.'],
    'Joelho flexionado foca o sóleo, que dá "largura" à panturrilha.', 'Usar as mãos para empurrar o apoio.'],
  [99, 'Panturrilha sentado com halteres', 'Panturrilha', 'Sóleo',
    ['Sentado, halteres apoiados sobre os joelhos e pontas dos pés em uma anilha.', 'Eleve os calcanhares.', 'Desça devagar.'],
    'Alternativa para quem treina em casa.', 'Amplitude curta.'],
  [100, 'Elevação de calcanhar com joelhos flexionados', 'Panturrilha', 'Sóleo',
    ['Em pé com joelhos levemente flexionados.', 'Eleve os calcanhares mantendo a flexão dos joelhos.', 'Desça controlando.'],
    'Mantenha o ângulo do joelho constante durante toda a série.', 'Estender os joelhos na subida.'],
];

// Planos de treino prontos (bônus). Cada item: [id do exercício, séries x repetições]
export const planos = [
  {
    nome: 'Iniciante — Full Body (3x por semana)',
    descricao: 'Para quem está começando. Faça segunda, quarta e sexta. Descanso de 60–90s entre séries.',
    dias: [
      { nome: 'Treino A', itens: [[75, '3 x 10'], [5, '3 x 10'], [12, '3 x 10'], [24, '3 x 12'], [82, '3 x 12'], [67, '3 x 30s']] },
      { nome: 'Treino B', itens: [[73, '3 x 12'], [6, '3 x 10'], [16, '3 x 12'], [27, '3 x 12'], [86, '3 x 12'], [69, '3 x 10']] },
    ],
  },
  {
    nome: 'Intermediário — ABC (6x por semana)',
    descricao: 'A/B/C repetido duas vezes na semana. Descanso de 60–120s. Aumente a carga quando completar todas as repetições.',
    dias: [
      { nome: 'A — Peito, ombros e tríceps', itens: [[5, '4 x 8'], [2, '3 x 10'], [7, '3 x 12'], [24, '3 x 10'], [27, '4 x 12'], [46, '3 x 12'], [45, '3 x 12']] },
      { nome: 'B — Costas, posterior de ombro e bíceps', itens: [[12, '4 x 10'], [15, '3 x 8'], [17, '3 x 10'], [32, '3 x 15'], [30, '3 x 15'], [35, '3 x 10'], [40, '3 x 12']] },
      { nome: 'C — Pernas e abdômen', itens: [[75, '4 x 8'], [73, '3 x 12'], [70, '3 x 15'], [79, '3 x 10'], [83, '3 x 12'], [95, '4 x 15'], [61, '3 x 12']] },
    ],
  },
  {
    nome: 'Avançado — ABCDE (5x por semana)',
    descricao: 'Um grupo muscular por dia com alto volume. Descanso de 60–120s, técnicas de intensidade na última série.',
    dias: [
      { nome: 'A — Peito', itens: [[1, '4 x 8'], [6, '4 x 10'], [3, '3 x 12'], [11, '3 x 15'], [10, '3 x máx']] },
      { nome: 'B — Costas', itens: [[21, '4 x 6'], [13, '4 x máx'], [15, '4 x 8'], [16, '3 x 12'], [14, '3 x 15'], [18, '4 x 12']] },
      { nome: 'C — Ombros', itens: [[26, '4 x 8'], [27, '4 x 15'], [28, '3 x 12'], [31, '4 x 15'], [32, '3 x 15'], [25, '3 x 12']] },
      { nome: 'D — Pernas', itens: [[75, '4 x 8'], [74, '4 x 10'], [76, '3 x 10'], [80, '4 x 10'], [82, '3 x 12'], [98, '4 x 15'], [95, '4 x 15']] },
      { nome: 'E — Braços e abdômen', itens: [[48, '4 x 8'], [44, '3 x 10'], [51, '3 x 15'], [33, '4 x 10'], [36, '3 x 10'], [42, '3 x 12'], [59, '4 x 15']] },
    ],
  },
  {
    nome: 'Foco em glúteos e pernas (2x por semana)',
    descricao: 'Pode ser combinado com os treinos de membros superiores do plano ABC. Descanso de 60–90s.',
    dias: [
      { nome: 'Dia 1 — Glúteo máximo', itens: [[91, '2 x 20 passos'], [86, '4 x 10'], [76, '3 x 10'], [80, '3 x 10'], [87, '3 x 15'], [89, '3 x 20']] },
      { nome: 'Dia 2 — Glúteo médio e posterior', itens: [[88, '2 x 12'], [75, '4 x 10'], [81, '3 x 10'], [83, '3 x 12'], [93, '4 x 15'], [90, '3 x 15'], [97, '3 x 15']] },
    ],
  },
];
